// ORD 2023
CREATE TABLE IF NOT EXISTS Person (
    id INTEGER AUTO_INCREMENT NOT NULL,
    fornavn VARCHAR(15),
    etternavn VARCHAR(20),
    fodselsdato DATE NOT NULL,
    personnr CHAR(11),
    telefonnr CHAR(8),
    email VARCHAR(30),
    by VARCHAR(15),
    gatenavn VARCHAR(30),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Bruker (
    id INTEGER AUTO_INCREMENT NOT NULL,
    brukernavn VARCHAR(30),
    passord VARCHAR(255),
    PRIMARY KEY (id)
);

// ORD 2022
CREATE TABLE IF NOT EXISTS Bestilling (
    BID INTEGER AUTO_INCREMENT NOT NULL,
    BORD INTEGER,
    MOTTATT TIMESTAMP,
    VARER VARCHAR(255),
    PRIMARY KEY (BID),
    KID INTEGER,
    FOREIGN KEY (KID) REFERENCES Kunde(KID)
);

INSERT INTO Kunde (KID, NAVN, MOBIL, EPOST, PASSORD) VALUES ( 1, 'Sander', '87654321', 'sander.oslomet@webprog.no', 'Passord123' );

CREATE TABLE IF NOT EXISTS Kunde (
    KID INTEGER AUTO_INCREMENT NOT NULL,
    NAVN VARCHAR(50),
    MOBIL VARCHAR(8),
    EPOST VARCHAR(50),
    PASSORD VARCHAR(100),
    PRIMARY KEY (KID)
);