// Ord2023
CREATE TABLE Person (
    id INTEGER AUTO_INCREMENT NOT NULL,
    fornavn VARCHAR(15),
    etternavn VARCHAR(20),
    fodselsdato DATE NOT NULL,
    personnr CHAR(11),
    telefonnr CHAR(8),
    email VARCHAR(30),
    by VARCHAR(15),
    gatenavn VARCHAR(30),
    PRIMARY KEY (id)
);

CREATE TABLE Bruker (
    id INTEGER AUTO_INCREMENT NOT NULL,
    brukernavn VARCHAR(30),
    passord VARCHAR(255),
    PRIMARY KEY (id)
);

// Ord2022
CREATE TABLE Bestilling (
    BID INTEGER AUTO_INCREMENT NOT NULL,
    KID INTEGER,
    BORD INTEGER,
    MOTTATT TIMESTAMP,
    VARER VARCHAR(255),
    PRIMARY KEY (BID),
    FOREIGN KEY (KID) REFERENCES Kunde
);

CREATE TABLE Kunde (
    KID INTEGER AUTO_INCREMENT NOT NULL,
    NAVN VARCHAR(50),
    MOBIL VARCHAR(8),
    EPOST VARCHAR(50),
    PASSORD VARCHAR(100),
    PRIMARY KEY (KID)
);

INSERT INTO Kunde (NAVN, MOBIL, EPOST, PASSORD) VALUES ('Sander', '12345678', 'admin.oslomet@webprog.no', 'Admin123');
INSERT INTO Kunde (NAVN, MOBIL, EPOST, PASSORD) VALUES ('Marie', '87654321', 'mod.uio@juss.no', 'Mod123');